"""Thin facade for Stage B research helpers."""

from __future__ import annotations

from grados.research import (
    AuditCitationMarker,
    AuditedClaim,
    AuditEvidenceItem,
    CitationGraphEdge,
    CitationGraphItem,
    CitationGraphNode,
    CitationGraphResult,
    CitationGraphSummary,
    CitingPaperItem,
    ClaimMapEntry,
    CommonReferenceItem,
    ComparisonEvidenceItem,
    DraftAuditResult,
    EvidenceGridBlock,
    EvidenceGridResult,
    EvidenceGridRow,
    FullContextPaper,
    FullContextResult,
    FullContextSection,
    PaperComparisonResult,
    PaperComparisonRow,
    audit_draft_support,
    build_evidence_grid,
    compare_papers,
    get_citation_graph,
    get_papers_full_context,
)
from grados.research.evidence_pack import (
    prepare_evidence_pack,
    read_evidence_pack,
    verify_evidence_pack,
)
from grados.research.external_synthesis import (
    audit_external_synthesis_result,
    prepare_external_synthesis_packet,
    preview_external_synthesis_packet,
    save_external_synthesis_result,
)
from grados.research.pack_audit import (
    audit_answer_against_pack,
    suggest_missing_evidence,
)

__all__ = [
    "AuditCitationMarker",
    "AuditEvidenceItem",
    "AuditedClaim",
    "CitationGraphEdge",
    "CitationGraphItem",
    "CitationGraphNode",
    "CitationGraphResult",
    "CitationGraphSummary",
    "ClaimMapEntry",
    "CitingPaperItem",
    "CommonReferenceItem",
    "ComparisonEvidenceItem",
    "DraftAuditResult",
    "EvidenceGridBlock",
    "EvidenceGridResult",
    "EvidenceGridRow",
    "FullContextPaper",
    "FullContextResult",
    "FullContextSection",
    "PaperComparisonResult",
    "PaperComparisonRow",
    "audit_draft_support",
    "audit_answer_against_pack",
    "audit_external_synthesis_result",
    "build_evidence_grid",
    "compare_papers",
    "get_citation_graph",
    "get_papers_full_context",
    "prepare_evidence_pack",
    "prepare_external_synthesis_packet",
    "preview_external_synthesis_packet",
    "read_evidence_pack",
    "save_external_synthesis_result",
    "suggest_missing_evidence",
    "verify_evidence_pack",
]
