"""Thin facade for Stage B research helpers."""

from __future__ import annotations

from grados.research import (
    AuditCitationMarker,
    AuditedClaim,
    AuditEvidenceItem,
    CitationGraphEdge,
    CitationGraphItem,
    CitationGraphNode,
    CitationGraphResult,
    CitationGraphSummary,
    CitingPaperItem,
    ClaimMapEntry,
    CommonReferenceItem,
    ComparisonEvidenceItem,
    DraftAuditResult,
    EvidenceGridBlock,
    EvidenceGridResult,
    EvidenceGridRow,
    FullContextPaper,
    FullContextResult,
    FullContextSection,
    PaperComparisonResult,
    PaperComparisonRow,
    audit_draft_support,
    build_evidence_grid,
    compare_papers,
    get_citation_graph,
    get_papers_full_context,
)

__all__ = [
    "AuditCitationMarker",
    "AuditEvidenceItem",
    "AuditedClaim",
    "CitationGraphEdge",
    "CitationGraphItem",
    "CitationGraphNode",
    "CitationGraphResult",
    "CitationGraphSummary",
    "ClaimMapEntry",
    "CitingPaperItem",
    "CommonReferenceItem",
    "ComparisonEvidenceItem",
    "DraftAuditResult",
    "EvidenceGridBlock",
    "EvidenceGridResult",
    "EvidenceGridRow",
    "FullContextPaper",
    "FullContextResult",
    "FullContextSection",
    "PaperComparisonResult",
    "PaperComparisonRow",
    "audit_draft_support",
    "build_evidence_grid",
    "compare_papers",
    "get_citation_graph",
    "get_papers_full_context",
]
